DROP TABLE IF EXISTS replacements;
DROP TABLE IF EXISTS parts;
DROP TABLE IF EXISTS car_systems;
DROP TABLE IF EXISTS cars;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    create_date TIMESTAMP,
    enabled     BOOLEAN      NOT NULL,
    last_update TIMESTAMP
);
CREATE UNIQUE INDEX users_email_index ON users (email);


CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE cars
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    brand       VARCHAR(255),
    model       VARCHAR(255),
    color       VARCHAR(255),
    year        INTEGER,
    description VARCHAR(255),
    user_id     INTEGER      NOT NULL,
    create_date TIMESTAMP,
    last_update TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE car_systems
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255),
    car_id INTEGER NOT NULL,
    FOREIGN KEY (car_id) REFERENCES cars (id) ON DELETE CASCADE
);


CREATE TABLE parts
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interval_date INTEGER DEFAULT 25,
    interval_dist INTEGER DEFAULT 10000,
    name          VARCHAR(255),
    prolongation  INTEGER,
    car_system_id INTEGER,
    car_id        INTEGER,
    create_date   TIMESTAMP,
    last_update   TIMESTAMP,
    FOREIGN KEY (car_id) REFERENCES cars (id) ON DELETE CASCADE,
    FOREIGN KEY (car_system_id) REFERENCES car_systems (id)
);


CREATE TABLE replacements
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mileage             INTEGER NOT NULL,
    name                VARCHAR(255),
    part_name           VARCHAR(255),
    reason              VARCHAR(255),
    description         VARCHAR(255),
    part_id             INTEGER,
    prev_replacement_id INTEGER,
    create_date         TIMESTAMP,
    FOREIGN KEY (part_id) REFERENCES parts (id) ON DELETE CASCADE,
    FOREIGN KEY (prev_replacement_id) REFERENCES replacements (id)
);